# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f078fe76a06d0c9f3f2eabf77d28e3513580ee7d24925a81ccde4330e0ff17684862f94581b48fd9b0e3ac48563a645f0f2f352aea64e8a094bcf8ad9631199a

test:
  secret_key_base: 24e3f9c0e5d8df000c334a8347c209e7c9311e55e6cc2097c8e3c56159b9b3f0a8bf83a6df97a30d222703cea6783062be65a59db2de4b1615fb14fb0808e8c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
